#! /bin/sh

[ -z $(pgrep sxhkd) ] && sxhkd &

bspc monitor -d www term code multi comm VI

bspc config border_width         2
bspc config window_gap           10

# Colors
bspc config focused_border_color \#cc6666
bspc config normal_border_color  \#2a2d30
bspc config presel_border_color none

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

nitrogen --restore
[ -z $(pgrep mpd) ] && mpd
[ -z $(pgrep transmission) ] && tranmission-daemon
[ -z $(pgrep dunst) ] && dunst &
xrdb ~/.Xresources
[ -z $(pgrep polybar) ] && polybar bsp &
compton -b
